[general]
start = "bun run dev"
packageManager = "bun"
cookbookPort = 8000

[projects.__test__]
port = 9000
name = "Test"
type = "milkio"
typiaMode = "generation"
autoStart = true
prisma = [
    { mode = "development", migrateMode = "push", migrateDatabaseUrl = "file:./dev.db" },
    { mode = "production", migrateMode = "push", migrateDatabaseUrl = "file:./prod.db" },
]
