[general]
start = "bun run dev"
packageManager = "npm"
cookbookPort = 8000

[projects.__test__]
port = 9000
name = "Test"
type = "milkio"
runtime = "deno"
typiaMode = "generation"
autoStart = true
drizzle = [
    { mode = "development", migrateMode = "migrate", migrateDatabaseUrl = "memory://" },
    { mode = "production", migrateMode = "migrate", migrateDatabaseUrl = "memory://" },
]
watcher = ["echo hello world"]
