name: milkio-workspace
services:
  mysql:
    image: mysql:8.0.30
    restart: always
    ports:
      - "63306:3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./.database-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  postgres:
    image: postgres:17.5
    restart: always
    ports:
      - "65432:5432"
    volumes:
      - ./.database-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=default