/**
 * The content of this file is automatically generated by Typia.
 * It can be edited in the /packages/cookbook-dto/src/* file, and each time you run bun run dev, the generated file will be synced to another location based on the content of the /develop.ts.
 */

export interface CookbookOptions {
  projects: Record<
    string,
    {
      type: "milkio" | "custom";
      port: number;
      start: string;
      build: string;
      meta: Partial<{
        inspect: boolean;
      }>;
      runtime?: "node" | "deno" | "bun";
      name?: string;
      lazyRoutes?: boolean;
      watcher?: Array<string>;
      autoStart?: boolean;
      autoStartDelay?: number;
      connectTestUrl?: string;
      drizzle?: Array<{
        mode: string;
        migrateDatabaseUrl: string;
        migrateMode: "generate" | "push" | "any";
        schemaDir?: string;
      }>;
    }
  >;
  general: {
    start: string;
    packageManager: string;
    cookbookPort: number;
    modes: Array<string>;
  };
  config: {
    [key: string]: string | number | boolean;
  };
}

export type CookbookActionParams =
  | {
      type: "milkio@ping";
    }
  | {
      type: "milkio@logger";
      log: Array<any>;
    }
  | {
      type: "milkio@template";
      name: string;
      fsPath: string;
      template: string;
    }
  | {
      type: "workers@list";
    }
  | {
      type: "workers@get";
      key: string;
      index: number;
    };
export type CookbookSubscribeEmits =
  | {
      type: "workers@stdout";
      key: string;
      chunk: string;
    }
  | {
      type: "workers@state";
      key: string;
      state: "running" | "stopped";
      code: number | null | "kill" | "running";
    }
  | {
      type: "watcher@change";
      event: "rename" | "change";
      path: string;
    }
  | {
      type: "milkio@logger";
      log: Array<any>;
    };
